version: 2
models:
  - name: products
    description: Product dimension table. The grain of the table is one row per product.
    columns:
      - name: product_id
        description: ""
        meta:
          dimension:
            type: string
      - name: product_name
        description: ""
        meta:
          dimension:
            type: string
      - name: product_type
        description: ""
        meta:
          dimension:
            type: string
      - name: product_description
        description: ""
        meta:
          dimension:
            type: string
      - name: is_food_item
        description: ""
        meta:
          dimension:
            type: boolean
      - name: is_drink_item
        description: ""
        meta:
          dimension:
            type: boolean
      - name: product_price
        description: ""
        meta:
          dimension:
            type: number
